/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AirlineManager;

import Business.AirlineDirectory;
import Business.Airlines;
import Business.FlightDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;

/**
 *
 * @author Tanny
 */
public class ManageFlightSchedulesJPanel extends javax.swing.JPanel {

   JPanel panel;
   AirlineDirectory airdir;
   FlightDirectory fd = new FlightDirectory();
   Object row[]= new Object[1];
   int seat;
   Airlines a;
    public ManageFlightSchedulesJPanel(AirlineDirectory airdir,JPanel panel, Airlines a) {
        initComponents();
        this.panel=panel;
        this.airdir=airdir;
        this.a=a;
        DefaultComboBoxModel dm=new DefaultComboBoxModel();
        for(Airlines air : airdir.getAirlineDir()){
            row[0]=air.getAirlinerName();
            seat=air.getNumAirplanes();
            //dm  = new DefaultComboBoxModel(row);
            //dm.addElement(row[0]);
            //comboBox.addItem(dm);
            comboBox.addItem(row[0]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("Create Schedule");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View Schedule");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton1)
                        .addGap(80, 80, 80)
                        .addComponent(jButton2)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //comboBox.getSelectedItem();
        String item = (String) comboBox.getItemAt(comboBox.getSelectedIndex());
        ScheduleFlightsJPanel sfj = new ScheduleFlightsJPanel(fd, item, panel, seat, airdir);
        panel.add("ScheduleFlightsJPanel",sfj);
        CardLayout layout = (CardLayout)panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String item = (String) comboBox.getItemAt(comboBox.getSelectedIndex());
        ViewScheduleJPanel v = new ViewScheduleJPanel(fd,item,panel, seat,airdir,a);
        panel.add("ViewScheduleJPanel",v);
        CardLayout layout = (CardLayout)panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
