/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AirlineManager;

import Business.AirlineDirectory;
import Business.Airlines;
import Business.FlightDirectory;
import Business.Flights;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tanny
 */
public class ScheduleFlightsJPanel extends javax.swing.JPanel {

    String item;
    JPanel panel;
    int seat;
    FlightDirectory fd;
    AirlineDirectory airdir;
    public ScheduleFlightsJPanel(FlightDirectory fd,String item, JPanel panel, int seat, AirlineDirectory airdir) {
        initComponents();
        this.panel=panel;
        this.item=item;
        this.seat=seat;
        this.airdir=airdir;
        airlineTxt.setText(item);
        this.fd=fd;
        seatTxt.setText(String.valueOf(seat));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sourceTxt = new javax.swing.JTextField();
        destTxt = new javax.swing.JTextField();
        depTxt = new javax.swing.JTextField();
        arrTxt = new javax.swing.JTextField();
        seatTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        airlineTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        hourTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        minTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        monBox = new javax.swing.JComboBox();
        date = new javax.swing.JTextField();

        jLabel1.setText("Source");

        jLabel2.setText("Destination");

        jLabel3.setText("Departure Time(HH:MM)");

        jLabel4.setText("Arrival Time(HH:MM)");

        jLabel5.setText("Seats available to schedule");

        destTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destTxtActionPerformed(evt);
            }
        });

        seatTxt.setEditable(false);
        seatTxt.setEnabled(false);

        jLabel6.setText("Date");

        jLabel7.setText("Airlines");

        airlineTxt.setEditable(false);
        airlineTxt.setEnabled(false);

        jButton1.setText("Create Schedule");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Duration of travel");

        jLabel9.setText("hr");

        jLabel10.setText("min");

        jButton2.setText("< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        monBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(56, 56, 56)
                        .addComponent(jButton1)
                        .addGap(28, 237, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(monBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(depTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(arrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(destTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sourceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(airlineTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(hourTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(minTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(airlineTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sourceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(destTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(monBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(minTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        panel.remove(this);
        CardLayout layout = (CardLayout)panel.getLayout();
        layout.previous(panel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void destTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Flights f =new Flights();
        f= fd.addFlight();
        try{
        f.setSource(sourceTxt.getText());
        f.setDestination(destTxt.getText());
        f.setDepTime(depTxt.getText());
        String mon=(String) monBox.getItemAt(monBox.getSelectedIndex()); 
        f.setMonth(mon);
        f.setHour(Integer.parseInt(hourTxt.getText()));
        f.setMin(Integer.parseInt(minTxt.getText()));
        f.setArrTime(arrTxt.getText());
        f.setItem(item);
        f.setSeat(seat);
        airdir.setFlightdir(fd);
        fd.setFlights(f);
        int flag =0;
        switch((String) monBox.getItemAt(monBox.getSelectedIndex())){
            case "JAN":
            case "MAR":
            case "MAY":
            case "JUL":
            case "AUG":
            case "OCT":
            case "DEC":
                        flag=1;
                        break;
            case "FEB":
                        flag =2;
                        break;
          }
        if(Integer.parseInt(date.getText())>=1 && Integer.parseInt((date.getText()))<=30 && flag ==0 ||
               Integer.parseInt(date.getText())>=1 && Integer.parseInt((date.getText()))<=31 && flag ==1 ||
               Integer.parseInt(date.getText())>=1 && Integer.parseInt((date.getText()))<=28 && flag ==2){
                    f.setDate(Integer.parseInt(date.getText()));
                    if(!sourceTxt.getText().equalsIgnoreCase(destTxt.getText())){
                        if(!(Integer.parseInt(hourTxt.getText())>13) && 
                           !(Integer.parseInt(minTxt.getText())>61)){
                            char c= ':';
                            if((depTxt.getText().charAt(2))==c && (arrTxt.getText().charAt(2))==c){
                            JOptionPane.showMessageDialog(null, "Flight details saved!");
                            sourceTxt.setText("");
                            destTxt.setText("");
                            depTxt.setText("");
                            hourTxt.setText("");
                            minTxt.setText("");
                            arrTxt.setText("");
                            date.setText("");
                            }
                            else{
                            JOptionPane.showMessageDialog(null, "Wrong time format for arrival/departure time");
                            fd.removeFlight(f);
                            sourceTxt.setText("");
                            destTxt.setText("");
                            depTxt.setText("");
                            hourTxt.setText("");
                            minTxt.setText("");
                            arrTxt.setText("");
                            date.setText("");
                            }
                    }
                        else{
                            JOptionPane.showMessageDialog(null, "Wrong time format for duration of travel");
                            fd.removeFlight(f);
                            sourceTxt.setText("");
                            destTxt.setText("");
                            depTxt.setText("");
                            hourTxt.setText("");
                            minTxt.setText("");
                            arrTxt.setText("");
                            date.setText("");
                        }
                    }
                    else{
                      JOptionPane.showMessageDialog(null, "Source and destination cannot be same");
                      fd.removeFlight(f);
                      sourceTxt.setText("");
                      destTxt.setText("");
                      depTxt.setText("");
                      hourTxt.setText("");
                      minTxt.setText("");
                      arrTxt.setText("");
                      date.setText("");
                    }
            }
            else{
                      JOptionPane.showMessageDialog(null, "Wrong inputs for date");
                      fd.removeFlight(f);
                      sourceTxt.setText("");
                      destTxt.setText("");
                      depTxt.setText("");
                      hourTxt.setText("");
                      minTxt.setText("");
                      arrTxt.setText("");
                      date.setText("");
            }
        
        }
        catch(NumberFormatException n){
            JOptionPane.showMessageDialog(null, "Please enter numeric values");
            fd.removeFlight(f);
          }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlineTxt;
    private javax.swing.JTextField arrTxt;
    private javax.swing.JTextField date;
    private javax.swing.JTextField depTxt;
    private javax.swing.JTextField destTxt;
    private javax.swing.JTextField hourTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField minTxt;
    private javax.swing.JComboBox monBox;
    private javax.swing.JTextField seatTxt;
    private javax.swing.JTextField sourceTxt;
    // End of variables declaration//GEN-END:variables
}
