/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Customer;

import Business.AirlineDirectory;
import Business.Flights;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Tanny
 */
public class MoreDetailsJPanel extends javax.swing.JPanel {

    JPanel panel;
    AirlineDirectory airline;
    Flights f;
    public MoreDetailsJPanel(Flights f,JPanel panel, AirlineDirectory airline) {
        initComponents();
        this.panel=panel;
        this.airline=airline;
        this.f=f;
        airlineTxt.setText(f.getItem());
        sourceTxt.setText(f.getSource());
        destTxt.setText(f.getDestination());
        dateTxt.setText(String.valueOf(f.getDate())+"-"+f.getMonth());
        depTime.setText(f.getDepTime());
        arrTxt.setText(f.getArrTime());
        hourTxt.setText(String.valueOf(f.getHour()));
        minTxt.setText(String.valueOf(f.getMin()));
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        sourceTxt = new javax.swing.JTextField();
        destTxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JTextField();
        depTime = new javax.swing.JTextField();
        arrTxt = new javax.swing.JTextField();
        hourTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        minTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        airlineTxt = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Source");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, -1, -1));

        jLabel2.setText("Destination");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));

        jLabel3.setText("Date");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setText("Expected Departure Time");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setText("Expected Arrival Time");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 169, -1, -1));

        jLabel6.setText("Duration of travel");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 197, -1, -1));

        jButton1.setText("<  Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 228, -1, -1));

        sourceTxt.setEditable(false);
        sourceTxt.setEnabled(false);
        add(sourceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 114, -1));

        destTxt.setEditable(false);
        destTxt.setEnabled(false);
        add(destTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 114, -1));

        dateTxt.setEditable(false);
        dateTxt.setEnabled(false);
        add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 114, -1));

        depTime.setEditable(false);
        depTime.setEnabled(false);
        add(depTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 114, -1));

        arrTxt.setEditable(false);
        arrTxt.setEnabled(false);
        arrTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrTxtActionPerformed(evt);
            }
        });
        add(arrTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 114, -1));

        hourTxt.setEditable(false);
        hourTxt.setEnabled(false);
        add(hourTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 35, -1));

        jLabel7.setText("hr");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        minTxt.setEditable(false);
        minTxt.setEnabled(false);
        add(minTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 35, -1));

        jLabel8.setText("min");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jLabel9.setText("Airline");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, -1, -1));

        airlineTxt.setEditable(false);
        airlineTxt.setEnabled(false);
        add(airlineTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 114, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void arrTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panel.remove(this);
        CardLayout layout = (CardLayout)panel.getLayout();
        layout.previous(panel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlineTxt;
    private javax.swing.JTextField arrTxt;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JTextField depTime;
    private javax.swing.JTextField destTxt;
    private javax.swing.JTextField hourTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField minTxt;
    private javax.swing.JTextField sourceTxt;
    // End of variables declaration//GEN-END:variables
}
