/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package designInterface;
import business.VitalSignHistory;
import business.VitalSigns;
import javax.swing.JOptionPane;
/**
 *
 * @author Tanmayee Kalluri
 */
public class CreateVitalJPanel extends javax.swing.JPanel {

    private VitalSignHistory vsh;
    public CreateVitalJPanel(VitalSignHistory vsh) {
        initComponents();
        this.vsh= vsh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tempTxt = new javax.swing.JTextField();
        bpTxt = new javax.swing.JTextField();
        pulseTxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();

        jLabel1.setText("Temperature");

        jLabel2.setText("Blood Pressure");

        jLabel3.setText("Pulse");

        jLabel4.setText("Date");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tempTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(bpTxt)
                            .addComponent(pulseTxt)
                            .addComponent(dateTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(saveBtn)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tempTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pulseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(saveBtn)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        VitalSigns v = vsh.addVitals();
        try{
            try{
                if(bpTxt.getText().isEmpty())
                  JOptionPane.showMessageDialog(null,"Please re-enter the value for blood pressure." ); 
                  //vsh.deleteVitals(v);
                }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Please re-enter the value for blood pressure." );
                bpTxt.setText("");
                vsh.deleteVitals(v);
                 }
        try{
            if(tempTxt.getText().isEmpty()){
                  JOptionPane.showMessageDialog(null,"Please re-enter the value for temperature." );  
                  //vsh.deleteVitals(v);
                }
           }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please re-enter the value for temperature." );
            tempTxt.setText("");
            vsh.deleteVitals(v);
        }
        try{
            if(pulseTxt.getText().isEmpty()){
                  JOptionPane.showMessageDialog(null,"Please re-enter the value for pulse." );
                  //vsh.deleteVitals(v);
                }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please re-enter the value for pulse." );
            pulseTxt.setText("");
            vsh.deleteVitals(v);
        }
        v.setDate(dateTxt.getText());
        if(!pulseTxt.getText().isEmpty() && !dateTxt.getText().isEmpty() && !bpTxt.getText().isEmpty() && !tempTxt.getText().isEmpty()){
        v.setBloodPressure(Double.parseDouble(bpTxt.getText()));
        v.setTemperature(Double.parseDouble(tempTxt.getText()));
        v.setPulse(Integer.parseInt(pulseTxt.getText()));
        JOptionPane.showMessageDialog(null,"Created successfully" );
        bpTxt.setText("");
        tempTxt.setText("");
        pulseTxt.setText("");
        dateTxt.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null,"Please re-enter");
            bpTxt.setText("");
            tempTxt.setText("");
            pulseTxt.setText("");
            dateTxt.setText("");
            vsh.deleteVitals(v);
           }
    }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"Please re-enter" );
        bpTxt.setText("");
        tempTxt.setText("");
        pulseTxt.setText("");
        dateTxt.setText("");
        vsh.deleteVitals(v);
      }
        
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bpTxt;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField pulseTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField tempTxt;
    // End of variables declaration//GEN-END:variables
}
